name: NutriByte CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'PRODUCTION_DOCUMENTATION.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Deploy to Heroku
        if: success()
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "nutribyte-mill1300"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          stack: "heroku-24"
          procfile: "web: node server/integrated.js"
